name: salah_construction
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.14
  rflutter_alert: ^2.0.4
  intl: ^0.17.0
  provider: ^6.0.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:

  background_image: "assets/images/salah-construction-splash-screen-2.png"